version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
      # - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    # command: gunicorn DockerDjango.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    #comment our below ports for deployment
    ports:
      - '8000:8000'
    expose:
      - 8000
    env_file: 
      - .env
    depends_on:
      - db
volumes:
  dbdata: